/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import Clases.Personas;
import clases.ListaS;

/**
 *
 * @author Jesus
 */
public class ListasSimples extends javax.swing.JDialog {

    /**
     * Creates new form ListasSimples
     */
    public void limpiar() {
        txtID.setText("");
        txtNombe.setText("");
        txtApellido.setText("");
        txtNodo.setText("");
        txtID.requestFocusInWindow();
        cmbSexo.setSelectedIndex(0);
        cmbOpciones.setSelectedIndex(0);
    }

    public ListasSimples(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
       

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScroll = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        cmdAgregar = new javax.swing.JButton();
        cmdModificar = new javax.swing.JButton();
        cmdEliminar = new javax.swing.JButton();
        cmdMostrar = new javax.swing.JButton();
        cmdLimpiar = new javax.swing.JButton();
        cmbOpciones = new javax.swing.JComboBox<>();
        txtNodo = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jAraea = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        txtID = new javax.swing.JTextField();
        txtNombe = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbSexo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lista Simple");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Vrinda", 0, 24)); // NOI18N
        jLabel1.setText("Lista Simple");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 19, -1, -1));
        jPanel1.add(jScroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 1175, 100));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdAgregar.setText("Aceptar");
        cmdAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAgregarActionPerformed(evt);
            }
        });
        jPanel2.add(cmdAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        cmdModificar.setText("Modificar");
        jPanel2.add(cmdModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        cmdEliminar.setText("Eliminar");
        cmdEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEliminarActionPerformed(evt);
            }
        });
        jPanel2.add(cmdEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        cmdMostrar.setText("Mostrar");
        cmdMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMostrarActionPerformed(evt);
            }
        });
        jPanel2.add(cmdMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, -1, -1));

        cmdLimpiar.setText("Limpiar");
        cmdLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLimpiarActionPerformed(evt);
            }
        });
        jPanel2.add(cmdLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, -1, -1));

        cmbOpciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Agregar inicio", "Agregar final", "Agregar entre nodos", "ELiminar inicio", "ELiminar final", "ELiminar entre nodos" }));
        cmbOpciones.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbOpcionesItemStateChanged(evt);
            }
        });
        cmbOpciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbOpcionesActionPerformed(evt);
            }
        });
        jPanel2.add(cmbOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, -1));

        txtNodo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNodoKeyTyped(evt);
            }
        });
        jPanel2.add(txtNodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 60, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 90, 300, 190));

        jAraea.setEditable(false);
        jAraea.setColumns(20);
        jAraea.setRows(5);
        jScrollPane2.setViewportView(jAraea);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 158, 458, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIDKeyTyped(evt);
            }
        });
        jPanel3.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 43, 80, -1));

        txtNombe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombeKeyTyped(evt);
            }
        });
        jPanel3.add(txtNombe, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 81, 80, -1));

        txtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoKeyTyped(evt);
            }
        });
        jPanel3.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 119, 80, -1));

        jLabel2.setText("Identificacion");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 46, -1, -1));

        jLabel3.setText("Nombre");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 84, -1, -1));

        jLabel4.setText("Apellido");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 122, -1, -1));

        jLabel5.setText("Sexo");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 160, -1, -1));

        cmbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Indefinido", "Femenino", "Masculino" }));
        jPanel3.add(cmbSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 157, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 88, 290, 200));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1256, 533));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAgregarActionPerformed
        String id = txtID.getText();
        String nombre = txtNombe.getText();
        String apellido = txtApellido.getText();
        String sexo = cmbSexo.getSelectedItem().toString();
        
        int operaciones = cmbOpciones.getSelectedIndex();
        ListaS ls = new ListaS();
        Personas p = new Personas(id, nombre, apellido, sexo);
        switch (operaciones) {
            case 0:

                
                
                ls.agregarInicio(p);
                limpiar();
                jScroll.setViewportView(new PaintDibujo(ls.size(), txtNombe.getText(), ls));
                break;
            case 1:
                jAraea.setText(id + " " + nombre + " " + apellido + " " + sexo);
                ls.agregarFinal(p);
                jScroll.setViewportView(new PaintDibujo(ls.size(), txtNombe.getText(), ls));
                break;
            case 2:
                int nodo = Integer.parseInt(txtNodo.getText());
                jAraea.setText(id + " " + nombre + " " + apellido + " " + sexo);
                ls.agregarEntreNodos(p,nodo);
                jScroll.setViewportView(new PaintDibujo(ls.size(), txtNombe.getText(), ls));
                break;
            case 3:
                ls.eliminarInicio();
                jScroll.setViewportView(new PaintDibujo(ls.size(), txtNombe.getText(), ls));
                break;
            case 4:
                ls.eliminarFinal();
                jScroll.setViewportView(new PaintDibujo(ls.size(), txtNombe.getText(), ls));
            break;
            case 5:
                int nodo1 = Integer.parseInt(txtNodo.getText()); 
                ls.eliminarEntreNodos(nodo1);
                jScroll.setViewportView(new PaintDibujo(ls.size(), txtNombe.getText(), ls));
                break;
                
        }


    }//GEN-LAST:event_cmdAgregarActionPerformed

    private void txtIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(evt.getKeyChar())) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtIDKeyTyped

    private void txtNodoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNodoKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(evt.getKeyChar())) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtNodoKeyTyped

    private void txtNombeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombeKeyTyped
        char c = evt.getKeyChar();
        if (Character.isDigit(c) || Character.isSpaceChar(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtNombeKeyTyped

    private void txtApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoKeyTyped
        char c = evt.getKeyChar();
        if (Character.isDigit(c) || Character.isSpaceChar(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtApellidoKeyTyped

    private void cmdLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLimpiarActionPerformed
        this.limpiar();
    }//GEN-LAST:event_cmdLimpiarActionPerformed

    private void cmdEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEliminarActionPerformed
        ListaS ls = new ListaS();
        ls.eliminarLista();
        jScroll.setViewportView(new PaintDibujo(ls.size(), "d", ls));
    }//GEN-LAST:event_cmdEliminarActionPerformed

    private void cmdMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMostrarActionPerformed
        ListaS ls = new ListaS();

        ls.mostrarPerosnas(jAraea);
    }//GEN-LAST:event_cmdMostrarActionPerformed

    private void cmbOpcionesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbOpcionesItemStateChanged

        
        
    }//GEN-LAST:event_cmbOpcionesItemStateChanged

    private void cmbOpcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOpcionesActionPerformed
    

 
    }//GEN-LAST:event_cmbOpcionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListasSimples.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListasSimples.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListasSimples.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListasSimples.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ListasSimples dialog = new ListasSimples(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbOpciones;
    private javax.swing.JComboBox<String> cmbSexo;
    private javax.swing.JButton cmdAgregar;
    private javax.swing.JButton cmdEliminar;
    private javax.swing.JButton cmdLimpiar;
    private javax.swing.JButton cmdModificar;
    private javax.swing.JButton cmdMostrar;
    private javax.swing.JTextArea jAraea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScroll;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNodo;
    private javax.swing.JTextField txtNombe;
    // End of variables declaration//GEN-END:variables
}
